
const mongoose = require('mongoose') ;


const Zone = mongoose.Schema({
   
    userid   : {   //the id of the owner
                    type : mongoose.Schema.Types.ObjectId  ,
                    ref  : 'user'   ,
                    required : true ,
                },
    apikey   : String , 
    name     : String ,
    location : String ,
    ttnid    : String //Zone idin ttn network 
    //apikey : String (can be generated by ttn api ,required to connect to application topic) 
});


module.exports = mongoose.model('zone' , Zone) ;


